// Downloads the latin subsets of a product's typefaces and inlines them as
// base64 data URIs, so every PDF build is reproducible without a network.
//
//   node scripts/fetch-fonts.mjs museum
//   node scripts/fetch-fonts.mjs flight
//
// The output is committed. Re-run it only to change the typefaces.
import { writeFile } from 'node:fs/promises';

const SETS = {
  // Marlow Museum Mysteries — slab, condensed signage, typewriter documents.
  museum: {
    out: 'assets/fonts/fonts.css',
    families:
      'family=Bitter:wght@600;700;900' +
      '&family=Oswald:wght@500;600' +
      '&family=Special+Elite' +
      '&family=Source+Sans+3:ital,wght@0,400;0,600;0,700;1,400' +
      '&family=Courier+Prime:ital,wght@0,400;0,700;1,400' +
      '&family=Caveat:wght@600',
  },
  // Kapture Flight School — industrial display, transport-signage condensed,
  // instrument mono. A deliberately different voice from the museum kit.
  flight: {
    out: 'assets/fonts/flight.css',
    families:
      'family=Archivo+Black' +
      '&family=Barlow+Condensed:wght@500;600;700' +
      '&family=Barlow:ital,wght@0,400;0,600;0,700;1,400' +
      '&family=Share+Tech+Mono' +
      '&family=Caveat:wght@600',
  },
};

const name = process.argv[2] ?? 'museum';
const set = SETS[name];
if (!set) throw new Error(`Unknown font set "${name}". Known: ${Object.keys(SETS).join(', ')}`);

const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';
const css = await (await fetch(`https://fonts.googleapis.com/css2?${set.families}&display=swap`,
  { headers: { 'User-Agent': UA } })).text();

// Keep only the `/* latin */` blocks: the kits are English-only and the other
// subsets would triple the embedded payload for no benefit.
const blocks = css.split('/*').filter((b) => /^\s*latin\s*\*\//.test(b));
if (blocks.length === 0) throw new Error('No latin subsets found in Google Fonts CSS');

let out = `/* Generated by scripts/fetch-fonts.mjs ${name} — do not edit by hand. */\n`;
for (const block of blocks) {
  const url = block.match(/url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/)?.[1];
  if (!url) continue;
  const bytes = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  const face = ('/*' + block)
    .replace(/url\(https:\/\/[^)]+\)/, `url(data:font/woff2;base64,${bytes.toString('base64')})`)
    .replace(/\s*unicode-range:[^;]+;/, '')
    .replace(/font-display:\s*swap;/, 'font-display: block;')
    .replace(/^\/\*\s*latin\s*\*\/\s*/, '');
  out += face.trim() + '\n\n';
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
  const style = block.match(/font-style:\s*(\w+)/)?.[1];
  console.log(`embedded ${family} ${weight} ${style} (${(bytes.length / 1024).toFixed(0)} kB)`);
}
await writeFile(set.out, out);
console.log(set.out);
