// Downloads the latin subsets of the kit's typefaces and inlines them as
// base64 data URIs, so every PDF build is reproducible without a network.
import { writeFile } from 'node:fs/promises';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Bitter:wght@600;700;900' +
  '&family=Oswald:wght@500;600' +
  '&family=Special+Elite' +
  '&family=Source+Sans+3:ital,wght@0,400;0,600;0,700;1,400' +
  '&family=Courier+Prime:ital,wght@0,400;0,700;1,400' +
  '&family=Caveat:wght@600&display=swap';

const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

// Keep only the `/* latin */` blocks: the kit is English-only and the other
// subsets would triple the embedded payload for no benefit.
const blocks = css.split('/*').filter((b) => /^\s*latin\s*\*\//.test(b));
if (blocks.length === 0) throw new Error('No latin subsets found in Google Fonts CSS');

let out = '/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n';
for (const block of blocks) {
  const url = block.match(/url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/)?.[1];
  if (!url) continue;
  const bytes = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  const face = ('/*' + block)
    .replace(/url\(https:\/\/[^)]+\)/, `url(data:font/woff2;base64,${bytes.toString('base64')})`)
    .replace(/\s*unicode-range:[^;]+;/, '')
    .replace(/font-display:\s*swap;/, 'font-display: block;')
    .replace(/^\/\*\s*latin\s*\*\/\s*/, '');
  out += face.trim() + '\n\n';
  const name = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
  const style = block.match(/font-style:\s*(\w+)/)?.[1];
  console.log(`embedded ${name} ${weight} ${style} (${(bytes.length / 1024).toFixed(0)} kB)`);
}
await writeFile('assets/fonts/fonts.css', out);
